version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: localizationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./LocalisationSheet.Server
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: Host=db;Port=5432;Database=localizationdb;Username=postgres;Password=postgres
    ports:
      - "5000:5000"   
    networks:
      - app-network

  frontend:
    build:
      context: ./LocalisationSheet.Client
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./LocalisationSheet.Client:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
