name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: localizationdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: LocalisationSheet.Client/package-lock.json
        
    - name: Restore dependencies
      run: |
        dotnet restore LocalisationSheet.Server/LocalisationSheet.Server.csproj
        dotnet restore LocalisationSheet.Server.Tests/Tests.Unit/Tests.Unit.csproj
      
    - name: Build
      run: dotnet build LocalisationSheet.Server/LocalisationSheet.Server.csproj --no-restore --configuration Release
      
    - name: Run unit tests
      run: dotnet test LocalisationSheet.Server.Tests/Tests.Unit/Tests.Unit.csproj --configuration Release --verbosity normal
      env:
        ConnectionStrings__Default: Host=localhost;Port=5432;Database=localizationdb;Username=postgres;Password=postgres
      
    - name: Build frontend
      run: |
        cd LocalisationSheet.Client
        npm ci
        npm run build 